spring.application.name=technomant-testtasak

# Must be > 45 characters
jwt.secret=

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
