spring.application.name=technomant-testtasak

jwt.secret=elephantelephantelephantelephantelephantelephant

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/technomant_testtask_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
